## 01a Experiment 1a: Category Membership - Items Task

### 0 Setup

In [10]:
import os
from openai import OpenAI
import random
import pandas as pd
import time
import csv

### 1 Functions

In [11]:
# Prompt Model to answer Questionnaire

def collect_output(client, prompt):
    response = client.chat.completions.create(model="deepseek-chat",messages=[{"role": "user","content": prompt}],stream=False)
    return response

### A. Items Task

In [12]:
# CATEGORIES
categories = ["Furniture","Fruit","Vehicle","Weapon","Vegetable", "Carpenter's tool", "Bird", "Sport", "Toy", "Clothing"] #from rosch1975a

# + "Furniture" category, but "furniture" excluded here, because using results from prompts experiment with prompt 6

In [ ]:
# Collect Answers from Model

items_reps = 30 #30

# retrieve API 
with open('', 'r') as file:
    api = file.read()     
client = OpenAI(api_key='', base_url="https://api.deepseek.com")

prompt_outputs = pd.DataFrame(columns=['model', 'prompt', 'prompt_id', 'runtime', 'category', 'output'])
model_output = pd.DataFrame()

for rep in range(items_reps): # max rep == 30

        rep_categories = categories.copy()  
        random.shuffle(rep_categories)
        
        for i in range(len(rep_categories)):

            current_prompt = f"""
            The procedure will be as follows: First you will be given the name or description of a category. Then you will write as many items included in that category as you can, in whatever order they happen to occur to you. The category is: "{rep_categories[i]}".
            Do not add any further details, only write the items that answer the instruction.
            Provide your answer in plain text as a comma-separated list of nouns.
            """
            
            start_time = time.time() 
            output = collect_output(client, current_prompt)
            end_time = time.time() 
            runtime = end_time - start_time
            model_output = pd.DataFrame({
                'model': 'deepseek-chat',
                'prompt': [current_prompt],
                'prompt_id': [6],
                'runtime': [runtime],
                'category': [rep_categories[i]],
                'output': [output]
            })
            
            prompt_outputs = pd.concat([prompt_outputs, model_output], ignore_index=True)

prompt_outputs.head()

C:\Users\AS\AppData\Local\Temp\ipykernel_13100\3626861569.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prompt_outputs = pd.concat([prompt_outputs, model_output], ignore_index=True)

,model,prompt,prompt_id,runtime,category,output
0,gemini-3-pro,\n The procedure will be as follows...,6,3.246853,Vehicle,ChatCompletion(id='767c0134-473b-4126-8b14-bb0...
1,gemini-3-pro,\n The procedure will be as follows...,6,5.227146,Fruit,ChatCompletion(id='61d9270f-177f-4043-8062-7cd...
2,gemini-3-pro,\n The procedure will be as follows...,6,3.196091,Sport,ChatCompletion(id='1e207e9a-bebb-45e1-be7f-6c2...
3,gemini-3-pro,\n The procedure will be as follows...,6,2.986753,Toy,ChatCompletion(id='d6f7f4de-1930-4fd1-9af4-2fa...
4,gemini-3-pro,\n The procedure will be as follows...,6,3.056621,Vegetable,ChatCompletion(id='eb634232-5fc9-446a-910f-ac7...

In [ ]:
prompt_outputs['output'] = prompt_outputs['output'].apply(lambda x: x.choices[0].message.content if x.choices else None)

In [26]:
prompt_outputs.head()

,model,prompt,prompt_id,runtime,category,output
0,gemini-3-pro,\n The procedure will be as follows...,6,3.246853,Vehicle,"car, truck, bicycle, motorcycle, bus, train, a..."
1,gemini-3-pro,\n The procedure will be as follows...,6,5.227146,Fruit,"Apple, Banana, Orange, Grape, Strawberry, Blue..."
2,gemini-3-pro,\n The procedure will be as follows...,6,3.196091,Sport,"Soccer, Basketball, Tennis, Baseball, American..."
3,gemini-3-pro,\n The procedure will be as follows...,6,2.986753,Toy,"ball, doll, teddy bear, action figure, buildin..."
4,gemini-3-pro,\n The procedure will be as follows...,6,3.056621,Vegetable,"carrot, broccoli, spinach, potato, onion, toma..."

In [27]:
prompt_outputs['model'] = 'deepseek-chat'

In [28]:
prompt_outputs

,model,prompt,prompt_id,runtime,category,output
0,deepseek-chat,\n The procedure will be as follows...,6,3.246853,Vehicle,"car, truck, bicycle, motorcycle, bus, train, a..."
1,deepseek-chat,\n The procedure will be as follows...,6,5.227146,Fruit,"Apple, Banana, Orange, Grape, Strawberry, Blue..."
2,deepseek-chat,\n The procedure will be as follows...,6,3.196091,Sport,"Soccer, Basketball, Tennis, Baseball, American..."
3,deepseek-chat,\n The procedure will be as follows...,6,2.986753,Toy,"ball, doll, teddy bear, action figure, buildin..."
4,deepseek-chat,\n The procedure will be as follows...,6,3.056621,Vegetable,"carrot, broccoli, spinach, potato, onion, toma..."
...,...,...,...,...,...,...
295,deepseek-chat,\n The procedure will be as follows...,6,3.103915,Vegetable,"carrot, potato, broccoli, spinach, lettuce, to..."
296,deepseek-chat,\n The procedure will be as follows...,6,15.135883,Weapon,"sword, gun, knife, bow, spear, axe, club, rifl..."
297,deepseek-chat,\n The procedure will be as follows...,6,108.747166,Clothing,"shirt, pants, dress, skirt, jacket, coat, swea..."
298,deepseek-chat,\n The procedure will be as follows...,6,7.472781,Vehicle,"car, truck, motorcycle, bicycle, bus, train, a..."
299,deepseek-chat,\n The procedure will be as follows...,6,3.920081,Carpenter's tool,"hammer, saw, chisel, screwdriver, tape measure..."

In [29]:
len(prompt_outputs)

300

In [ ]:
# take away NaN Answers
print("Number of rows:", len(prompt_outputs),"\n")
print("Number of rows after NA filtering:", len(prompt_outputs.dropna(inplace=True)))

In [31]:
prompt_outputs.to_csv(f'01_catmemexp_itemstask_allmodels_raw.csv',index=False, quoting=csv.QUOTE_ALL, encoding='utf-8', mode='a')