## 02b Experiment 1a: Category Membership - Attributes Task PreProcessing

In [1]:
# Setup
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import ast

In [ ]:
# Import Data

attributes_df  = pd.read_csv('01_catmemexp_attributestask_allmodels_raw_2.csv', dtype=str, quoting=csv.QUOTE_ALL, encoding = "utf-8")
attributes_df.head()

,model,prompt,prompt_id,runtime,category,frequency,item,output
0,Qwen/Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted, casual, lightweight, breathable, cotto..."
1,Qwen/Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted, casual, lightweight, cotton, breathabl..."
2,Qwen/Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable, casual, lightweight, short, versa..."
3,Qwen/Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted, casual, lightweight, cotton, quick-dry..."
4,Qwen/Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable, casual, lightweight, short, cotto..."

In [ ]:
# Processing Outputs

attributes_df = attributes_df[attributes_df.iloc[:, 0] != 'model']

attributes_df['model'] = attributes_df['model'].where(~attributes_df['model'].str.contains('/'), attributes_df['model'].str.split('/').str[1])
models = attributes_df['model'].unique()
print("Tested Models: \n", attributes_df['model'].unique(), "\n")

def modify_string(value):
    if isinstance(value, str):
        
        value = value.replace("_", " ")
        
        elements = [elem.strip() for elem in value.split(',')]

        modified_elements = []
        for elem in elements:  
                modified_elements.append(elem.strip())

        return ','.join(modified_elements)
    
    return value

attributes_df['output'] = attributes_df['output'].str.lower()
attributes_df['output'] = attributes_df['output'].apply(modify_string)
#attributes_df['output'] = attributes_df['output'].str.rstrip(string.punctuation).str.strip()  
# Remove the last element from the comma separated strings
#attributes_df['output'] = attributes_df['output'].apply(lambda x: ','.join(x.split(',')[:-1]))
# Remove the last element from the list of strings
#attributes_df['output_list'] = attributes_df['output_list'].apply(lambda x: x[:-1])

Tested Models:
 ['Qwen2.5-7B-Instruct' 'Qwen2.5-14B-Instruct' 'Qwen2.5-32B-Instruct'
 'Qwen2.5-72B-Instruct' 'Meta-Llama-3.1-8B-Instruct'
 'Meta-Llama-3.1-70B-Instruct']

In [ ]:
# Counting NA outputs

# Attributes
na_count = attributes_df['output'].isna().sum()
print(f"\nNumber of NA items outputs: {na_count}")
na_values = attributes_df[attributes_df['output'].isna()]
models_na_counts = na_values['model'].value_counts()
print("NA items for each model:")
print(models_na_counts)

Number of NA items outputs: 0
NA items for each model:
Series([], Name: count, dtype: int64)

In [20]:
# Entries check
print("\nItems Task nr. Outputs:")
attributes_df_counts = attributes_df['model'].value_counts()
print(attributes_df_counts)

Items Task nr. Outputs:
model
Meta-Llama-3.1-70B-Instruct    45
Qwen2.5-14B-Instruct           30
Meta-Llama-3.1-8B-Instruct     30
Qwen2.5-32B-Instruct           30
Qwen2.5-7B-Instruct            15
Qwen2.5-72B-Instruct           15
Name: count, dtype: int64

In [21]:
# Converting output column to list of items
attributes_df['output_list'] = attributes_df['output'].apply(lambda x: x.split(',') if isinstance(x, str) else [])
attributes_df.head()

,model,prompt,prompt_id,runtime,category,frequency,item,output,output_list
0,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted,casual,lightweight,breathable,cotton,qu...","[fitted, casual, lightweight, breathable, cott..."
1,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,breathable,sh...","[fitted, casual, lightweight, cotton, breathab..."
2,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,versatile...","[comfortable, casual, lightweight, short, vers..."
3,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,quick-dry,ela...","[fitted, casual, lightweight, cotton, quick-dr..."
4,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,cotton,qu...","[comfortable, casual, lightweight, short, cott..."

In [22]:
attributes_df.head()

,model,prompt,prompt_id,runtime,category,frequency,item,output,output_list
0,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted,casual,lightweight,breathable,cotton,qu...","[fitted, casual, lightweight, breathable, cott..."
1,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,breathable,sh...","[fitted, casual, lightweight, cotton, breathab..."
2,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,versatile...","[comfortable, casual, lightweight, short, vers..."
3,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,quick-dry,ela...","[fitted, casual, lightweight, cotton, quick-dr..."
4,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,cotton,qu...","[comfortable, casual, lightweight, short, cott..."

In [25]:
attributes_df.to_csv('trouble_items.csv',index=False, quoting=csv.QUOTE_ALL, encoding='utf-8')

In [12]:
## MANUAL PROCESSING ...

#### Cleaning

In [ ]:
attributes_df  = pd.read_csv('01_catmemexp_attributestask_allmodels_processed_2.csv', dtype=str, quoting=csv.QUOTE_ALL, encoding = "utf-8")
attributes_df.head()

In [ ]:
attributes_df['output_list_processed'] = attributes_df['output_list'].apply(ast.literal_eval)

In [28]:
attributes_df['output_list_processed'] = attributes_df['output_list'].copy()

In [ ]:
def process_outputs(row, transformations):
    processed_outputs = []
    for item in row['output_list_processed']: 
        processed_item = transformations.get(item, item)  
        if processed_item is not None:  
            processed_outputs.append(processed_item)
    return processed_outputs   

transformations = {
    "": None,
    " ": None}

attributes_df['output_list_processed'] = attributes_df.apply(lambda row: process_outputs(row, transformations), axis=1)
attributes_df.head()

,model,prompt,prompt_id,runtime,category,frequency,item,output,output_list,output_list_processed
0,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted,casual,lightweight,breathable,cotton,qu...","[fitted, casual, lightweight, breathable, cott...","[fitted, casual, lightweight, breathable, cott..."
1,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,breathable,sh...","[fitted, casual, lightweight, cotton, breathab...","[fitted, casual, lightweight, cotton, breathab..."
2,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,versatile...","[comfortable, casual, lightweight, short, vers...","[comfortable, casual, lightweight, short, vers..."
3,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,quick-dry,ela...","[fitted, casual, lightweight, cotton, quick-dr...","[fitted, casual, lightweight, cotton, quick-dr..."
4,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,cotton,qu...","[comfortable, casual, lightweight, short, cott...","[comfortable, casual, lightweight, short, cott..."

In [30]:
# remove None values
attributes_df.dropna(inplace=True)

In [31]:
#removing duplicates
attributes_df['output_list_processed'] = attributes_df['output_list_processed'].apply(lambda x: list(set(x)))

In [ ]:

# Function to filter items based on frequency
def filter_items(group):

    group['output_list_processed'] = group['output_list_processed'].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    )

    exploded = group['output_list_processed'].explode()
    
    attributes_count = exploded.value_counts()
    
    filtered_items = attributes_count[attributes_count > 1].index.tolist()

    group['output_list_processed_nonoise'] = group['output_list_processed'].apply(
        lambda x: [item for item in x if item in filtered_items]
    )
    
    return group

attributes_df = attributes_df.groupby(['model', 'category', 'item'], group_keys=False).apply(filter_items)

attributes_df.reset_index(drop=True, inplace=True)

attributes_df.head()

C:\Users\AS\AppData\Local\Temp\ipykernel_21828\1870716746.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  attributes_df = attributes_df.groupby(['model', 'category', 'item'], group_keys=False).apply(filter_items)

,model,prompt,prompt_id,runtime,category,frequency,item,output,output_list,output_list_processed,output_list_processed_nonoise
0,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted,casual,lightweight,breathable,cotton,qu...","[fitted, casual, lightweight, breathable, cott...","[cotton, versatile, elastic, shortsighted, lig...","[cotton, versatile, elastic, shortsighted, lig..."
1,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,breathable,sh...","[fitted, casual, lightweight, cotton, breathab...","[cotton, versatile, short, elasticated, lightw...","[cotton, versatile, short, elasticated, lightw..."
2,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,versatile...","[comfortable, casual, lightweight, short, vers...","[versatile, informal, short, lightweight, summ...","[versatile, short, lightweight, summer, casual..."
3,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,quick-dry,ela...","[fitted, casual, lightweight, cotton, quick-dr...","[short-length, cotton, versatile, quick-dry, e...","[short-length, cotton, versatile, quick-dry, e..."
4,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,cotton,qu...","[comfortable, casual, lightweight, short, cott...","[cotton, versatile, short, elasticated, quick-...","[cotton, versatile, short, elasticated, quick-..."

In [33]:
attributes_df.head()

,model,prompt,prompt_id,runtime,category,frequency,item,output,output_list,output_list_processed,output_list_processed_nonoise
0,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted,casual,lightweight,breathable,cotton,qu...","[fitted, casual, lightweight, breathable, cott...","[cotton, versatile, elastic, shortsighted, lig...","[cotton, versatile, elastic, shortsighted, lig..."
1,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,breathable,sh...","[fitted, casual, lightweight, cotton, breathab...","[cotton, versatile, short, elasticated, lightw...","[cotton, versatile, short, elasticated, lightw..."
2,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,versatile...","[comfortable, casual, lightweight, short, vers...","[versatile, informal, short, lightweight, summ...","[versatile, short, lightweight, summer, casual..."
3,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,quick-dry,ela...","[fitted, casual, lightweight, cotton, quick-dr...","[short-length, cotton, versatile, quick-dry, e...","[short-length, cotton, versatile, quick-dry, e..."
4,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,cotton,qu...","[comfortable, casual, lightweight, short, cott...","[cotton, versatile, short, elasticated, quick-...","[cotton, versatile, short, elasticated, quick-..."

In [ ]:
attributes_df['output_list'] = attributes_df['output_list'].apply(ast.literal_eval)

In [35]:
# Re-order output_list_processed
def reorder_column_processed(row):
    order_dict = {item: i for i, item in enumerate(row['output_list'])}
    return sorted(row['output_list_processed'], key=lambda x: order_dict.get(x, float('inf')))

attributes_df['output_list_processed'] = attributes_df.apply(reorder_column_processed, axis=1)

# Re-order output_list_processed_nonoise
def reorder_column_processedn(row):
    order_dict = {item: i for i, item in enumerate(row['output_list'])}
    return sorted(row['output_list_processed_nonoise'], key=lambda x: order_dict.get(x, float('inf')))

attributes_df['output_list_processed_nonoise'] = attributes_df.apply(reorder_column_processedn, axis=1)

In [36]:
attributes_df.head()

,model,prompt,prompt_id,runtime,category,frequency,item,output,output_list,output_list_processed,output_list_processed_nonoise
0,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.800426722,Clothing,average_frequency,shorts,"fitted,casual,lightweight,breathable,cotton,qu...","[fitted, casual, lightweight, breathable, cott...","[fitted, casual, lightweight, breathable, cott...","[fitted, casual, lightweight, breathable, cott..."
1,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.434558153,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,breathable,sh...","[fitted, casual, lightweight, cotton, breathab...","[fitted, casual, lightweight, cotton, breathab...","[fitted, casual, lightweight, cotton, breathab..."
2,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.316383362,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,versatile...","[comfortable, casual, lightweight, short, vers...","[comfortable, casual, lightweight, short, vers...","[comfortable, casual, lightweight, short, vers..."
3,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.374921083,Clothing,average_frequency,shorts,"fitted,casual,lightweight,cotton,quick-dry,ela...","[fitted, casual, lightweight, cotton, quick-dr...","[fitted, casual, lightweight, cotton, quick-dr...","[fitted, casual, lightweight, cotton, quick-dr..."
4,Qwen2.5-7B-Instruct,\r\n Write all of the attributes of...,6,1.430232048,Clothing,average_frequency,shorts,"comfortable,casual,lightweight,short,cotton,qu...","[comfortable, casual, lightweight, short, cott...","[comfortable, casual, lightweight, short, cott...","[comfortable, casual, lightweight, short, cott..."

In [ ]:
#attributes_df.to_csv('trouble_items.csv',index=False, quoting=csv.QUOTE_ALL, encoding='utf-8')